### ISSUE TITLE
How can I section by the day and month properties of a Date field?

### ISSUE THREAD

**Issue by JoseDelPino** [Whiffer/swiftdata-sectionedquery#2]
I want to section my models by its Date field but of course not up to the millisecond. Is this possible right now?

**Comment by Whiffer** [comment]
Assuming your models are sorted by that Date field, it's up to you to decide how your sections get grouped with what keypath you use as the `sectionIdentifier: ` .   You should be able to add a computed property to your model with a return value (e.g. String) that gives you your desired section grouping.
