### ISSUE TITLE
Lazy loading large lists

### ISSUE THREAD

**Issue by Magnuti** [Whiffer/swiftdata-sectionedquery#3]
Nice package!

Just checking in here since I am not very skilled with CoreData - does this package lazy load large lists? If we have 1000 elements in total we don't want to query all 1000 elements, but query as we scroll down the list.

**Comment by Whiffer** [comment]
Just checking... my package is designed for SwiftData and not CoreData, if that makes a difference.

In my own Apps, I have databases with many more than 1000 elements and I haven't noticed any performance issues.  When I do see performance issues, they are mostly related to the code implementing the UI and not the data model.

I found an interesting article that talks about CoreData/List performance issues. https://betterprogramming.pub/demystifying-swiftui-list-responsiveness-best-practices-for-large-datasets-d9719f01b719

Let me know if this helps. Thanks.

**Comment by Magnuti** [comment]
After some research I found out that `@Query` of course fetches all elements that matches the filter.

I created my own lazy loading logic by setting [fetchLimit](https://developer.apple.com/documentation/swiftdata/fetchdescriptor/fetchlimit)  on the FetchDescriptor. This is outside the scope of this package so I'll close this issue.

**Comment by Magnuti** [comment]
Oh an by the way I asked about Core Data since I saw that your code imported `CoreData`

**Comment by Whiffer** [comment]
Gotcha.  The only reason for the `CoreData` import was just to get the name of CoreData's Context Saved notification because SwiftData didn't start sending its `didDave` notification until Sequoia.

Thanks for reminding me. I just now updated the package to run correctly on both Sonoma and Sequoia.
