### ISSUE TITLE
Revise fatal errors

### ISSUE THREAD

**Issue by pschuette22** [Whiffer/swiftdata-sectionedquery#4]
https://github.com/Whiffer/swiftdata-sectionedquery/blob/5435d9a061067460b0857e3f44d25fc0872146ea/Sources/SectionedQuery/SectionedQuery.swift#L95

I love this solution, but am a little concerned about the fatals. I think this is an opinion on the framework that should be revisited.

#### 1. Convert fatalError to [assertionFailure](https://developer.apple.com/documentation/swift/assertionfailure(_:file:line:))
Pros: Simplest solution. Avoids throwing fatals in production
Cons: Swallows the error if you don't find it in a pre-release

#### 2. Pass an "Error Strategy"
```swift
enum ErrorStrategy {
   case fatal
   case assertion
   case log(Logger)

    func handle(_ error: any Error, file: StaticString = #file, line: UInt = #line) {
        ...
     } 
}
```

Pros: defers to implementer. Default to fatal to maintain functionality
Cons: Not sure, what are your thoughts?

#### 3. Pass an Error Handler

```swift
public protocol ErrorHandler {
    func handle(error: any Error, file: StaticString, line: UInt)
}

extension ErrorHandler {
   public static var fatal: ErrorHandler { FatalErrorHandler() }

   public func handle(_ error: any Error, file: StaticString = #file, line: UInt = #line) {
       handle(error: error, file: file, line: line)
   } 
}

struct FatalErrorHandler: ErrorHandler {
   func handle(_ error: any Error, file: StaticString, line: UInt) {
        fatalError(error. localizedDescription, file: file, line: line)
   }
}
```
Pros: Customizable
Cons: More to maintain

**Comment by Whiffer** [comment]
You make a very good point.  Frankly, to me, this package fills such an obvious missing hole in SwiftData that I expected Apple to make it obsolete long ago.  I was not really expecting this package would ever need to be used as-is in a production App. 

My initial thought is towards something simple that gives the implementer an option besides fatal error, which is most likely a variation of your option 1.  I will dig into this when I have some time to dedicate to an appropriate solution.  Thanks.

**Comment by Whiffer** [comment]
After trying for a while,  in all of my internal testing I have not been able to trigger any of those fatalErrors.   It would seem to me that they would be much more likely to occur from code bugs during development rather than from bad data in production, so I think adding error handlers just for this might be overkill.  However, if your experience is different, I would be interested in finding easy ways to test examples of those "fatal errors".

In any case, I did take a stab at restructuring `fetchSectionedResults()` using your proposal #1, where I just log the issue and return empty results instead of crashing.  Let me know what you think.

```
    private func fetchSectionedResults() {
        
        let fetchDescriptor = FetchDescriptor<Result>(predicate: self.configuration.predicate, sortBy: self.configuration.sortDescriptors)
        
        if let fetchResults = try? self.modelContext.fetch(fetchDescriptor) {
            
            let sectionIdentifiers = fetchResults.map { $0[keyPath: self.configuration.sectionIdentifier] }
            let uniqueSectionIdentifiers = Array(sectionIdentifiers.uniqued())

            let sections = uniqueSectionIdentifiers.map { sectionIdentifier in
                
                if let firstIndex = fetchResults.firstIndex(where: { sectionIdentifier == $0[keyPath: self.configuration.sectionIdentifier] } ),
                   let lastIndex = fetchResults.lastIndex(where: { sectionIdentifier == $0[keyPath: self.configuration.sectionIdentifier] } ) {

                    let sectionElements = Array(fetchResults[firstIndex...lastIndex])
                    return SectionedResults<SectionIdentifier, Result>.Section(id: sectionIdentifier, elements: sectionElements )
                } else {
                    assertionFailure("Internal consistency check failed. Unable to create a Section from the fetch results.")
                    return SectionedResults<SectionIdentifier, Result>.Section(id: sectionIdentifier, elements: [Result]() )
                }
            }
            
            self.sections = sections
        } else {
            assertionFailure("ModelContext.fetch() threw an exception.")
            self.sections = [SectionedResults<SectionIdentifier, Result>.Section<Result>]()
        }
    }

}


```

**Comment by pschuette22** [comment]
Makes sense. Agreed, surprised Apple hasn't addressed this. I'd say that while that's the case right now, we don't know how the framework evolves, including error usage. 

Only point here would be that `try?` is just a catch under the hood but it's reassigning the result to optional (enum(Some) ) and then unwraps it. It's more concise to just catch the error:

```swift
private func fetchSectionedResults() {
    try {
        try fetchSectionedResultsWithError()
    } catch {
       assertionFailure(error.localizedDescription)
       // Maybe just 
    }
}

private func fetchSectionedResultsWithError() throws {
        
        let fetchDescriptor = FetchDescriptor<Result>(predicate: self.configuration.predicate, sortBy: self.configuration.sortDescriptors)
 
        sections = try self.modelContext.fetch(fetchDescriptor)
              .map { $0[keyPath: self.configuration.sectionIdentifier] }
              .uniqued()
              .compactMap { sectionIdentifier in
                
                if let firstIndex = fetchResults.firstIndex(where: { sectionIdentifier == $0[keyPath: self.configuration.sectionIdentifier] } ),
                   let lastIndex = fetchResults.lastIndex(where: { sectionIdentifier == $0[keyPath: self.configuration.sectionIdentifier] } ) {

                    let sectionElements = Array(fetchResults[firstIndex...lastIndex])
                    return SectionedResults<SectionIdentifier, Result>.Section(id: sectionIdentifier, elements: sectionElements )
                } else {
                    assertionFailure("Internal consistency check failed. Unable to create a Section from the fetch results.")
                    return nil
                }
    }
```

I just based this off of your original gist in the WebUI, pardon any syntax errors or misunderstandings.

**Comment by Whiffer** [comment]
Thanks for pushing me to clean up the error handling and to help make the code more readable in the process.  BTW, I think the original `fetchResults` has to be saved in order for the compactMap to work.  I have retested the happy path, but I am still unable to create test cases for the unhappy path.   Anyway, I just committed my changes.  Thanks again.
